#ifndef NAME_H
#define NAME_H
#include <raylib.h>
typedef struct {
	Texture2D dms;
	Texture2D usa;
	Texture2D vvid;
	Texture2D exit;
	Texture2D con;
	Texture2D vvid1;
	Texture2D exit1;
	Texture2D con1;
	Texture2D exit2;
	Texture2D con2;
	Sound err;
	Sound good;
	Font inter;
	Vector2 texts;
	bool v;
	bool vb;
	bool e;
	bool c;
	bool c1;
	int cp;
	bool cp1;
	bool pere;
	int peret;
	int fps;
	int time;
	int timee;
	int rub;
	char password[100];
	char password1[100];
	int pas;
	int k;
	float x;
}etap1;
etap1 Upload1(etap1 a);
etap1 Upload1v(etap1 a);
typedef struct {
	Image gif;
	Texture2D giph;
	Sound codmw2;
	int fps;
	int totalf;
	int f;
	int flast;
	int file;
} etap2;
etap2 LoadGif(const char* filename);
etap2 UpdateGif(etap2 b);
void DrawGif(etap2 b);
typedef struct {
	Texture2D fon;
	Texture2D dms;
	Texture2D accept;
	Texture2D accept1;
	Texture2D accept2;
	Texture2D accept3;
	Texture2D next;
	Texture2D next1;
	Texture2D next2;
	Texture2D textfield;
	Texture2D cencel;
	Texture2D cencel1;
	Texture2D cencel2;
	Texture2D scrol;
	Texture2D audiob;
	Texture2D audiob1;
	Texture2D povzunok;
	Texture2D povzunok1;
	Music autext;
	char *policy;
	char *loadText;
	char backupChar;
	Font mono;
	int tlenght;      
	int theght;
	int visiblechar;
	int timer;
	int currentlinew;
	int lastspase;
	int i;
	char tempt[2];
	float scrolly;      
	float fullHeight;
	float scrollBarY;
	float maxScroll;
	float progress;
	int linecount;
	bool dragging;
	float draggingofset;
	float newSliderY;
	float ratio;
	bool galochka;
	bool hover;
	bool nextb;
	bool cencelb;
	bool rub;
	int timern;
	int timerc;
	bool onoff;
	int tick;
	int x;
	int minutes;
	int seconds;
	int fps;
}etap3;
etap3 Upload3(etap3 c);
etap3 Drawtext(etap3 c);
#endif
