#ifndef NAME_H
#define NAME_H
#include <raylib.h>
typedef struct {
	Texture2D dms;
	Texture2D usa;
	Texture2D vvid;
	Texture2D exit;
	Texture2D con;
	Texture2D vvid1;
	Texture2D exit1;
	Texture2D con1;
	Texture2D exit2;
	Texture2D con2;
	Sound err;
	Sound good;
	Font inter;
	Vector2 texts;
	bool v;
	bool vb;
	bool e;
	bool c;
	bool c1;
	int cp;
	bool cp1;
	bool pere;
	int peret;
	int fps;
	int time;
	int timee;
	int rub;
	char password[100];
	char password1[100];
	int pas;
	int k;
	float x;
}etap1;
etap1 Upload1(etap1 a);
etap1 Upload1v(etap1 a);
typedef struct {
	Image gif;
	Texture2D giph;
	Sound codmw2;
	int fps;
	int totalf;
	int f;
	int flast;
	int file;
} etap2;
etap2 LoadGif(const char* filename);
etap2 UpdateGif(etap2 b);
void DrawGif(etap2 b);
typedef struct {
	Texture2D fon;
	Texture2D dms;
	Texture2D accept;
	Texture2D accept1;
	Texture2D accept2;
	Texture2D accept3;
	Texture2D next;
	Texture2D next1;
	Texture2D next2;
	Texture2D textfield;
	Texture2D cencel;
	Texture2D cencel1;
	Texture2D cencel2;
	Texture2D scrol;
	Texture2D audiob;
	Texture2D audiob1;
	Texture2D povzunok;
	Texture2D povzunok1;
	Music autext;
	char *policy;
	char *loadText;
	char backupChar;
	Font mono;
	int tlenght;      
	int theght;
	int visiblechar;
	int timer;
	int currentlinew;
	int lastspase;
	int i;
	char tempt[2];
	float scrolly;      
	float fullHeight;
	float scrollBarY;
	float maxScroll;
	float progress;
	int linecount;
	bool dragging;
	float draggingofset;
	float newSliderY;
	float ratio;
	bool galochka;
	bool hover;
	bool nextb;
	bool cencelb;
	bool rub;
	int timern;
	int timerc;
	bool onoff;
	int tick;
	int x;
	int minutes;
	int seconds;
	int fps;
}etap3;
etap3 Upload3(etap3 c);
etap3 Drawtext(etap3 c);
typedef struct {
	Texture2D file;
	Texture file1;
	Texture2D file2;
	float basedY;
	int time;
	bool f;
}FolderButton;
typedef struct {
	Texture2D fon;
	Texture2D dms;
	Texture2D field;
	Texture2D scroll;
	Texture2D bscroll;
	Texture2D file1;
	Texture2D infofile1;
	Texture file11;
	Texture file12;
	bool inf1;
	Texture2D file2;
	Texture2D infofile2;
	Texture file21;
	Texture2D file22;
	Texture2D file3;
	Texture2D file31;
	Texture2D file32;
	Texture2D file4;
	Texture2D file41;
	Texture2D file42;
	Texture2D file5;
	Texture2D file51;
	Texture2D file52;
	Texture2D file6;
	Texture2D file61;
	Texture2D file62;
	Texture2D file7;
	Texture2D file71;
	Texture2D file72;
	Texture2D close;
	Texture2D close1;
	Texture2D close2;
	bool inf2;
	int timef1;
	int timef2;
	int timef3;
	int timef4;
	int timef5;
	int timef6;
	int timef7;
	int timec;
	float scrollOffset;
	float wheel;
	float maxScroll;
	float dragging;
	bool draggingofset;
	float bscrollY;
	float scrollY;
	float ratio;
	FolderButton folders[5];
	int i;
	bool f1;
	bool f2;
}etap4;
etap4 Upload4(etap4 d);
void Draw4(etap4 d);
etap4 UpdateScrollLogic(etap4 d);
int DrawFolderButton(FolderButton* btn, float scrollOffset);
typedef struct {
	Texture2D fon;
	Texture2D novebar;
	Texture2D novedit;
	Texture2D scroll;
	Texture2D close;
	Texture2D close1;
	Texture2D close2;
	Texture2D back;
	Texture2D back1;
	Texture2D back2;
	Texture2D bscroll;
	Texture2D editb;
	Texture2D editb1;
	Texture2D textf1;
	Texture2D textf2;
	Texture2D textf3;
	Texture2D textf4;
	Texture2D textf5;
	Texture2D textf6;
	Texture2D textf7;
	Texture2D winp;
	Texture2D continueb;
	Texture2D continueb1;
	Texture2D exit;
	Texture2D exit1;
	Texture2D saveb;
	Texture2D saveb1;
	Texture2D saveb2;
	Texture2D saveb3;
	Font inter;
	int timeb;
	int timec;
	float wheel;
	float scrollOffset;
	float scrollY;
	float maxScroll;
	bool dragging;
	float draggingofset;
	float ratio;
	float scrolloffset;
	char textBuffer[20480];
	bool isFileLoaded;
	float texth;
	float textl;
	float currentline;
	int linecout;
	char tempt[2];
	int lastspase;
	int i;
	bool edit;
	int letter;
	int k;
	bool bs;
	bool enter;
	int x;
	char* lastNewline;
	char* lastLine;
	bool cursor;
	float cursorY;
	int j;
	bool left;
	bool right;
	bool up;
	bool down;
	int len;
	int currStart;
	int offset;
	int prevEnd;
	int prevStart;
	int prevLen;
	int nextStart;
	int nextEnd;
	int nextLen;
	int currentLineStart;
	char tempLine[1024];
	int segLen;
	int byteSize;
	int delSize;
	const char* utf8char;
	bool wp;
	char password[20];
	char password1[20];
	int i1;
	int lettp;
	bool ok;
	bool correct;
	int times;
	bool save;
}etap5;
etap5 Upload5(etap5 e);
void Draw5(etap5 e, bool f1, bool f2, bool f3, bool f4, bool f5, bool f6, bool f7);
etap5 Scrollogic(etap5 e);
etap5 textfile(etap5 e,bool f1, bool f2, bool f3, bool f4, bool f5, bool f6, bool f7);
etap5 editmode(etap5 e);
etap5 editpassword(etap5 e);
void Savefile(etap5 e, bool f1, bool f2, bool f3, bool f4, bool f5, bool f6, bool f7);
#endif
